export const FETCH_LIB_DETAILS_STARTED = 'FETCH_LIB_DETAILS_STARTED';
export const FETCH_LIB_DETAILS_SUCCESS = 'FETCH_LIB_DETAILS_SUCCESS';
export const FETCH_LIB_DETAILS_FAILURE = 'FETCH_LIB_DETAILS_FAILURE';