export const RECEIVE_POSTS_LIBS = 'RECEIVE_POSTS_LIBS';
export const REQUEST_POSTS_LIBS = 'REQUEST_POSTS_LIBS';
export const INVALIDATE_LIBS = 'REQUEST_POSTS_LIBS';
export const UPDATE_LIBS = 'UPDATE_LIBS';